drop table if exists storedb.users;
create table storedb.users (id bigint generated by default as identity (increment 1 start 3) not null, password varchar(255), username varchar(255), primary key (id));
INSERT INTO storedb.users VALUES ( 1, 'admin', 'admin'), (2, 'jan', 'jan');
